import type { EvalReport } from '../types/api'

function triggerDownload(content: string, filename: string, mime: string): void {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function downloadReportJson(report: EvalReport): void {
  const content = JSON.stringify(report, null, 2)
  triggerDownload(content, `verdict_${report.run_id.slice(0, 8)}.json`, 'application/json')
}

export function downloadReportMarkdown(report: EvalReport): void {
  const ts = new Date(report.timestamp).toLocaleString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })
  const pct = (v: number) => `${Math.round(v * 100)}%`

  const passed = Math.round(report.pass_rate * report.total_tests)
  const failed = report.total_tests - passed

  const allFailureModes: Record<string, number> = {}
  for (const stats of Object.values(report.category_breakdown)) {
    for (const [mode, count] of Object.entries(stats.failure_modes)) {
      allFailureModes[mode] = (allFailureModes[mode] ?? 0) + (count as number)
    }
  }

  const lines: string[] = [
    `# Verdict Evaluation Report`,
    ``,
    `**Run ID:** \`${report.run_id}\`  `,
    `**Target:** ${report.target_system}  `,
    `**Date:** ${ts}  `,
    ...(report.verdict_version ? [`**Verdict version:** ${report.verdict_version}  `] : []),
    ``,
    `## Summary`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Pass rate | ${pct(report.pass_rate)} |`,
    ...(report.pass_rate_ci_low != null && report.pass_rate_ci_high != null
      ? [`| 95% CI | ${pct(report.pass_rate_ci_low)}–${pct(report.pass_rate_ci_high)} |`]
      : []),
    `| Total tests | ${report.total_tests} |`,
    `| Passed | ${passed} |`,
    `| Failed | ${failed} |`,
    ``,
    `## By Category`,
    ``,
    `| Category | Total | Passed | Failed | Pass Rate |`,
    `|----------|-------|--------|--------|-----------|`,
    ...Object.entries(report.category_breakdown).map(([cat, s]) =>
      `| ${cat} | ${s.total} | ${s.passed} | ${s.failed} | ${pct(s.pass_rate)} |`
    ),
  ]

  if (Object.keys(allFailureModes).length > 0) {
    lines.push(``, `## Failure Modes`, ``, `| Mode | Count |`, `|------|-------|`)
    for (const [mode, count] of Object.entries(allFailureModes).sort((a, b) => b[1] - a[1])) {
      lines.push(`| ${mode} | ${count} |`)
    }
  }

  const criticals = Object.entries(report.category_breakdown)
    .flatMap(([, s]) => s.critical_failures)
  if (criticals.length > 0) {
    lines.push(``, `## Critical Failures`, ``)
    for (const id of criticals) lines.push(`- \`${id}\``)
  }

  lines.push(``, `---`, `*Generated by verdict-eval ${report.verdict_version ?? ''}*`)

  triggerDownload(lines.join('\n'), `verdict_${report.run_id.slice(0, 8)}.md`, 'text/markdown')
}
